// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZehUSKxTClTYDa2JWXi5UwlmZ8AEJSoE',
    appId: '1:1060805639621:web:e11a77c55876fd27731fac',
    messagingSenderId: '1060805639621',
    projectId: 'group1-cd189',
    authDomain: 'group1-cd189.firebaseapp.com',
    storageBucket: 'group1-cd189.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_KhpXAqQ3UKQCbwAPDVZkOo-JkRcOsv4',
    appId: '1:1060805639621:android:357547cb910b1e9d731fac',
    messagingSenderId: '1060805639621',
    projectId: 'group1-cd189',
    storageBucket: 'group1-cd189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYyqAwWNXAqeKzdNPmnuRkIIpmgoLs_WQ',
    appId: '1:1060805639621:ios:a57336d2d3a702b4731fac',
    messagingSenderId: '1060805639621',
    projectId: 'group1-cd189',
    storageBucket: 'group1-cd189.firebasestorage.app',
    iosBundleId: 'com.example.g1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYyqAwWNXAqeKzdNPmnuRkIIpmgoLs_WQ',
    appId: '1:1060805639621:ios:a57336d2d3a702b4731fac',
    messagingSenderId: '1060805639621',
    projectId: 'group1-cd189',
    storageBucket: 'group1-cd189.firebasestorage.app',
    iosBundleId: 'com.example.g1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZehUSKxTClTYDa2JWXi5UwlmZ8AEJSoE',
    appId: '1:1060805639621:web:939ddb22535a7cd4731fac',
    messagingSenderId: '1060805639621',
    projectId: 'group1-cd189',
    authDomain: 'group1-cd189.firebaseapp.com',
    storageBucket: 'group1-cd189.firebasestorage.app',
  );
}
